server:
  port: 9070
 
spring:
  application:
    name: bahiazone-service
  datasource:
    url: jdbc:mysql://localhost:3306/bahiazone_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: devuser
    password: DevUser!74#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true