server:
  port: 9070
  servlet:
    contextPath: /bahiazone-service/api/v1
spring:
  application:
    name: bahiazone-service
  datasource:
    url: jdbc:mysql://localhost:3306/bahiazone_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: devuser
    password: DevUser!74#
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    